#!/usr/local/bin/zsh

pip install -U pip setuptools
pip install ipython tox

if [ -f requirements.txt ]; then
    pip install -r requirements.txt
fi

if [ -f test-requirements.txt ]; then
    pip install -r test-requirements.txt
fi
