#!/bin/bash

if ! which aws &>/dev/null; then
  echo "can't find awscli tool"
  exit 1
fi

set -x

$(aws --profile $AWS_ECR_PROFILE ecr get-login --no-include-email)

docker tag "$1" "$AWS_ECR_HOST/$1"

docker push "$AWS_ECR_HOST/$1"
