#!/bin/bash

ps aux 2>&1 | \
    grep -v '/System' | \
    grep -v '/usr/libexec' | \
    grep -v '/sbin/' | \
    grep -v 'ps aux' | \
    grep -v 'sysmond\|autofsd\|ssh-agent\|automountd\|SFLSharedPrefsTo\|AppleCameraAssistant\|corestoragehelperd\|Terminal\|aslmanager\|XPCServices' | \
    grep -v 'login -pf' | \
    grep -v ' -zsh' | \
    grep -v 'ssh.*mux' | \
    grep -v Flux | grep -iv vyprvpn | grep -v 'Little Snitch' | grep -v SizeUp | grep -v onepassword | grep -v ipcserver | \
    grep -v SpotifyWebHelper |  grep -v fusefs_txantfs | \
    grep -v $0
